FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /app
COPY DockerWithStatic.csproj DockerWithStatic.csproj
RUN dotnet restore DockerWithStatic.csproj
COPY . .
RUN dotnet publish -c Release -o /output --no-restore --nologo
