name: dockerstatic-blazor-wasm
static_sites:
  - name: site
    github:
      repo: zetroot/DockerWithStatic
      branch: master
      deploy_on_push: true
    dockerfile_path: Dockerfile.wasm
    output_dir: /output/wwwroot
    index_document: index.html
    catchall_document: index.html
