name: dockerstatic-blazor-wasm
static_sites:
  - name: site
    github:
      repo: zetroot/DockerStatic
      branch: master
      deploy_on_push: true
    dockerfile_path: Dockerfile.wasm
    output_dir: /app/publish/wwwroot
    index_document: index.html
    catchall_document: index.html
